# Generated by Django 5.2.17 on 2026-09-15 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='business',
            options={'ordering': ['name'], 'verbose_name': 'Business', 'verbose_name_plural': 'Businesses'},
        ),
    ]
