# Generated by Django 5.2.17 on 2026-09-27 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_seed_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(choices=[('inventory', 'Inventory'), ('sales', 'Sales'), ('purchases', 'Purchases'), ('suppliers', 'Suppliers'), ('deliveries', 'Deliveries'), ('reports', 'Reports'), ('advanced_reports', 'Advanced reports')], max_length=50)),
                ('value', models.CharField(default='true', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='billing.plan')),
            ],
            options={
                'ordering': ['plan', 'feature'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'feature'), name='unique_plan_entitlement')],
            },
        ),
    ]
