# Generated by Django 5.2.17 on 2026-09-26 16:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_seed_plans'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanEntitlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=100)),
                ('value_type', models.CharField(choices=[('BOOLEAN', 'Boolean'), ('INTEGER', 'Integer')], max_length=20)),
                ('boolean_value', models.BooleanField(blank=True, null=True)),
                ('integer_value', models.IntegerField(blank=True, null=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entitlements', to='billing.plan')),
            ],
            options={
                'ordering': ['feature'],
                'constraints': [models.UniqueConstraint(fields=('plan', 'feature'), name='unique_plan_entitlement')],
            },
        ),
    ]
