# Generated by Django 5.2.17 on 2026-09-18 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['group', 'name'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='group',
            field=models.CharField(choices=[('ALCOHOLIC_DRINKS', 'Alcoholic Drinks'), ('SODA_AND_DRINKS', 'Soda & Drinks'), ('CIGARETTES_AND_TOBACCO', 'Cigarettes & Tobacco'), ('OTHER', 'Other')], default='OTHER', max_length=30),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
    ]
